### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by yaohw007** [LingHanChuJian/live2d-vue#1]
![image](https://user-images.githubusercontent.com/38714842/57071494-3607e400-6d0d-11e9-9f7c-12295210bf9d.png)
出现这个怎么解决呢？

**Comment by LingHanChuJian** [comment]
试着重新拉下最新的 看看 还有这个问题么, 另外可以 贴出具体代码么 ？

**Comment by LingHanChuJian** [comment]
@yaohw007

**Comment by Hemingwaycn** [comment]
我也碰到相同的问题，在页面中加入live2d标签就出现这个问题了

**Comment by LingHanChuJian** [comment]
@Hemingwaycn  模型是我提供的么？

**Comment by Hemingwaycn** [comment]
是的，重新安装后强制刷新浏览器后显示正常了
