### ISSUE TITLE
{toolsPosition: "right"}显示不符合预期效果

### ISSUE THREAD

**Issue by tsukiseele** [LingHanChuJian/live2d-vue#5]
![image](https://user-images.githubusercontent.com/28500231/64904095-44bcc980-d6f7-11e9-9d8c-80452cda16a8.png)

审查元素发现如下内容：
![image](https://user-images.githubusercontent.com/28500231/64904115-ba289a00-d6f7-11e9-9d1e-332e7b78c94f.png)

这里的 transform: translateX(10px) rotate(180deg); 会导致容器内的文本也会被旋转变换。
虽然可以通过自行实现Tools组件解决，但如果能在下版本修复就更好了！

**Comment by LingHanChuJian** [comment]
@tsukiseele  我已经修复了， 你拉下最新的代码

**Comment by tsukiseele** [comment]
@LingHanChuJian 好的非常感谢
