### ISSUE TITLE
can't load pictures

### ISSUE THREAD

**Issue by LydiaHappy** [LingHanChuJian/live2d-vue#6]
我clone了原项目在本地运行，看到的是这样的。
似乎没办法加载图片？
![QQ截图20200128040610](https://user-images.githubusercontent.com/34096767/73209622-9d12d600-4183-11ea-9fdb-4257ac23c854.png)

**Comment by LingHanChuJian** [comment]
emmm 本地运行不行 需要将人物模型放到服务器上 通过 链接 加载 @LydiaHappy  抱歉 这么久才回你
